server:
  port: 9090

spring:
  application:
    name: oyetalk-game-tp


  datasource:
    url: jdbc:mysql://139.9.181.241:13307/cyber_auth?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: STS2022mysql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    maxActive: 60
    initialSize: 6
    maxWait: 60000
    minIdle: 2
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connectionProperties: password=${password}
    passwordCallback: passwordCallback

mybatis:
   mapperLocations: classpath:mapper/**/*.xml
   typeAliasesPackage: com.oyetalk.*.domain.entity
   configuration.map-underscore-to-camel-case: true

jwt:
  pathPatterns:
   - /user/**
   - /admin/**
  excludePathPatterns:
    - /sso/**
  resourceHandlers:
    /static/**: classpath:/static/
    /oss/**: classpath:/oss/

openai:
  keys: ${openai_keys}
  model: gpt-3.5-turbo-0613
  maxTokens: 3000
  temperature: 0.8
  presencePenalty: 1
  frequencyPenalty: 0
  topP: 1
  openaiApi:
  imageApi:
  creditApi:
  stop:
  contextNum: 3